### ISSUE TITLE
Numeric updown control misplaced

### ISSUE THREAD

**Issue by fredatgithub** [dbelmont/ExpressionBuilder#7]
hello,
In ExpressionBuilder.Builder.winform V1.1, at startup,the first numeric updown control is hidden partly behind the between combobox.
Can you fix this ?
![display-bug](https://user-images.githubusercontent.com/6720055/28017662-88d89e0a-657a-11e7-8367-bdcde6bc8479.jpg)

**Comment by dbelmont** [comment]
Hi Fred,
I'm very sorry but wasn't able to reproduce this bug, besides that, this project is not really about the desktop application. That application is meant to be just a quick demo of what the library is about, so I hope you don't give up on the project just because of that. 😉 
Anyway, would you mind telling me what's Windows version you're using? I'll try a bit harder to fix it because, even if this app isn't the main portion of the project, I think it's still useful to get to know what you can expect from the library.
Many thanks,
David
